repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: check-date-format
        name: Check if the date in the qmd file is in proper format
        entry: sh shell_scripts/checkDate.sh
        language: system
        pass_filenames: false
        stages: [commit]
-   repo: local
    hooks:
    -   id: exclude-files-from-commit
        name: Exclude files from commit
        entry: sh shell_scripts/excludeFiles.sh
        language: system
        stages: [commit]
-   repo: local
    hooks:
    -   id: check-space-in-file
        name: Check file names are not proper
        entry: sh shell_scripts/checkSpace.sh
        language: system
        stages: [commit]
